apiVersion: v1
kind: Secret
metadata:
  name: hurgelt-api-secret
  namespace: hurgelt
type: Opaque
stringData:
  JWT_SECRET: change-me-before-deploying
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASS: ""
